### ISSUE TITLE
OCR Speed questions

### ISSUE THREAD

**Issue by lange59** [Calamari-OCR/calamari#144]
Hello,

I have somes issues with the speed of OCR.
In the paper presenting Calamari, a inference time of 3ms per image is announced with a GTX 1070.
Using the same GPU, i have 35ms inference time for image of the same size so a factor 10.

How can explain the difference ?

Using last version of git repo, tensorflow-2.0 and Cuda 10.1, GTX 1070

**Comment by amitdo** [comment]
https://arxiv.org/pdf/1807.02004.pdf

>The processing time of a single line highly depends on the network architecture, the line width, and the used hardware. All the time experiments were measured on a NVIDIA GTX **1080Ti** GPU if the software supports GPU usage and an Intel Xeon E5-2690 CPU. Preprocessing requires ca. 50 ms per line with a single process and drops to 6 ms when processing eight lines in parallel.

**Comment by lange59** [comment]
I agree, but without preprocessing my processing time seens to be too high.
The network is the default one. So i think i made mistake somewhere.

Can someone have some actual bench with the last version of Calamari ?
Perhaps the paper is valid for old code but not the new.

**Comment by ChWick** [comment]
My last benchmarks with the current version of calamari (1.0) are identic to the original publication, however, due to comparison, only the actual inference (time of the image in the network) is measured. This excludes any python overhead like loading and decoding/result generation.
The difference you are measuring includes the complete overhead.
The complete transcription of a line takes in my setup about 20ms using `--batch_size 50` and `-j 12`. Note that if you only transcribe a few lines in one call, the times are expected to be higher.
