### ISSUE TITLE
missing glyphs

### ISSUE THREAD

**Issue by ocrwork** [Calamari-OCR/calamari#150]
I wrote a perl script to analyze the extended prediction data, in order to flag lower confidence positions in the inferenced line of text. It works to some extent. I would like to detect positions where no character is output at all, to avoid having to proofread the entire output. I am thinking to look at (global start of character) - (global end of previous character), and compare it to the previous character's width (width from a hard coded table) If the spacing is much larger than the width of the previous character, there must be a large area with no character detected. Is there an alternative way to modify the network, so that when an area of black pixels is not recognized as any known character, it inferences some unique code to say that some character is there, but can't guess what it is?

**Comment by chreul** [comment]
i think the solution is to treat the blank (= no character) label differently. the extended prediction data output prunes positions where a blank is the top choice, getting rid of the (sometimes quite helpful) information that the second choice would have been label x with yy% confidence. this is also done within the confidence voting mechanism which isn't exactly great and has been annoying me for quite some time.
however, due to the particularities of blanks and their tendency to come in packs, solving this is not a trivial task. we will look into it but it will take some time.

**Comment by ocrwork** [comment]
Thank you, sounds like an improvement. My perl script detects missing glyphs ok, except for zero width diacritical marks. So, I am closing this issue.
