### ISSUE TITLE
calamari-cross-fold-train --max_parallel_models > 1 fails with oom error

### ISSUE THREAD

**Issue by ocrwork** [Calamari-OCR/calamari#157]
If if set --max_parallel_models to anything > 1, I get an out of memory error as soon as it tries to load the second model. I have a Titan RTX (24GB ram), so there should be plenty of room for 2 or more models. I am using the default network, and it is not that huge a model.
I am wondering if tensorflow grabs all the memory when it loads the first model, then there is nothing
to allocate for the second model?
If no one has a simple answer, I will try researching this myself. There seem to be several leads out there about this. tensorflow allow_growth?

**Comment by ChWick** [comment]
You are right! By default Tensorflow reserves a fixed amount of memory (I think around 80%-90%) of a GPUs ram, which is why an allocation of the second model fails.
Using the `allow_growth` parameter could solved this, however, we never trained several models on the same GPU simultaneously. Instead, we used several GPUs (and slurm for skeduling). I'd love to know whether this works, though!
