### ISSUE TITLE
How much is TOO MUCH

### ISSUE THREAD

**Issue by deepseek** [Calamari-OCR/calamari#167]
@ChWick @chreul @mikegerber 
Thank you for your hard work,

- Lets say that I have 100 GB of training data "text-lines", inwhich I will add various augmentations and noise, and by that I would be able to generate 300 GB of training data.
- At what point does the Calamari model stops making sense of the input training data?
- Can 300 GB of various spectrum of text-lines be trained using Calamari with 95+ accuracy?
and at what modifications to the settings
How much is TOO MUCH ?

**Comment by chreul** [comment]
hi, sorry for the late (or rather non-) reply.
as we have never worked with THAT much data, i can only give some pointers of what i would expect:
- assuming that the training data is representative for the data you plan to recognize, i don't really expect data augmentation to noticably improve the results at this stage since it is most effective when only few real data is available
- in my opinion "the Calamari model stops making sense of the training data" is not the best way to look at it because it sounds like the training process is "hurt" by the extensive amount of data which is not the case. i would rather say that you will pass the point of diminishing return quite "early" and at some point even heaps and heaps of data won't noteably improve the model anymore since "it has seen it all"
- regarding the 95+ accuracy: i guess this is impossible to say as it entirely depends on the "various spectrums of text lines". regarding settings: in my experience the default network structure does quite well even when dealing with extensive amounts of data. however, in your case, using a deeper network might be in order.

**Comment by deepseek** [comment]
Summarizing:
1. Don't fill what's already full
2. You might see the sun @ epoch 1
3. Metamorphosis in a dark box

@chreul 
Can your implementation predict unseen words & lines? Even after the conjugation of words?
hold some form of attention?
