### ISSUE TITLE
gt.txt question

### ISSUE THREAD

**Issue by usteiner9** [Calamari-OCR/calamari#169]
how do I get an gt.txt?

**Comment by chreul** [comment]
"gt" stands for "ground truth", so for example the text file "img.gt.txt" contains the actual textual content of a line ([not page!](https://github.com/Calamari-OCR/calamari/issues/170)) image "img.bin.png". if you want to use your own data i am afraid that you will have to transcribe lines by yourself in order to produce GT.
but before that, you will have to run some preceding steps like preprocessing and segmentation to get down to line level.
please see for example [here](https://www.danvk.org/2015/01/09/extracting-text-from-an-image-using-ocropus.html) and [here](https://www.danvk.org/2015/01/11/training-an-ocropus-ocr-model.html) to get a general understanding of the workflow and maybe try out [OCR4all](https://github.com/OCR4all) for an easy to use all in one solution.
