### ISSUE TITLE
Version ranges for requirements.txt

### ISSUE THREAD

**Issue by kba** [Calamari-OCR/calamari#179]
https://github.com/Calamari-OCR/calamari/blob/715ebcdd8672c72c39a533a49f01d4eb1b36a760/requirements.txt#L11

An explicit version range would be helpful, also for the other requirements

**Comment by maximeboulanger** [comment]
I had issues with calamari-train. I've installed these packages versions prior to calamari installation.

numpy==1.18.1
edit_distance==1.0.4
h5py==2.10.0
protobuf==3.13.0
tensorflow==2.2.0

It works fine for me. I'll check for versions ranges that are currently working.

**Comment by andbue** [comment]
I had some problems with calamari-train, training from scratch and tf 2.3 a while ago. They should be fixed in current master but could also depend on the python version used and whatnot. If you could provide some working version ranges for master, this would be very helpful for the next pypi release!

**Comment by bertsky** [comment]
Please fix this on the 1.0 branch, too – it will pull in TF 2.5 currently (which relies on h5py 3.1).

**Comment by bertsky** [comment]
> Please fix this on the 1.0 branch, too – it will pull in TF 2.5 currently (which relies on h5py 3.1).

@ChWick could you please re-open?
