### ISSUE TITLE
Check codec changes

### ISSUE THREAD

**Issue by edwardpwtsoi** [Calamari-OCR/calamari#186]
https://github.com/Calamari-OCR/calamari/blob/b120c51d874dc2b4f161c588017034c3f4a9a8cc/calamari_ocr/ocr/trainer.py#L178

Hi, I was reading the code base and when I get to the above line, I think it should be checking the length of c instead of checking whether c is zero or not right?

**Comment by andbue** [comment]
You are right, codec_changes is a tuple of empty lists in case there aren't any changes. Should now be fixed with [https://github.com/Calamari-OCR/calamari/commit/904c1189e47de166e43bfd43901c4f288ef22476](https://github.com/Calamari-OCR/calamari/commit/904c1189e47de166e43bfd43901c4f288ef22476).
Thanks for noticing!
