### ISSUE TITLE
Initialization time on inference

### ISSUE THREAD

**Issue by abdullahenesoncu** [Calamari-OCR/calamari#229]
I want to use Calamari as OCR service and want to initialize Calamari once and use in a session more than once.
However, when I send a number of images to predict function of MultiPredictor, everytime it takes some time for initialization. I mean that even I infere for an image or an hundred images, it takes about a second and it means(I think) there is some initialization time. Moreover, if I set number of processes to 50, this initialization step takes about 15 seconds.

**Comment by ChWick** [comment]
The reason is, that the predict function will create a a new process for parallel processing of the input images each time you call it.
To reduce the initialization time disable parallel execution of the preprocessing which is slower of course if you handle a large list of samples. Alternatively, pass a "generator" to the prediction function so that the parallel pipeline is initialized once and kept alive until the generator stops

**Comment by ChWick** [comment]
See also https://github.com/Calamari-OCR/calamari/issues/263
