### ISSUE TITLE
Demo notebook in the calamari_demo repo.

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#296]
Hello!
@andbue 
Please I need in this demo the arabic part it is existant in the ancient notebook when I'm asking you in this 
issue https://github.com/Calamari-OCR/calamari/issues/230
But now didn't exist.
Please give me access to this part.
Thanks in advance.

**Comment by andbue** [comment]
The demo notebook in https://github.com/andbue/calamari_demo is not part of calamari. It is not actively maintained and only documents what was necessary as part of a workshop at a certain point of time. Please don't open issues regarding it here.

That being said, the part with "Training models for Arabic, train on line images" is still in the Notebook. As you can see from the history, it has not been changed since the first commit.
