### ISSUE TITLE
Questions regarding the data split for UW3

### ISSUE THREAD

**Issue by alwc** [Calamari-OCR/calamari#6]
Hi,

I'm trying to reproduce the result in the Calamari paper (https://arxiv.org/abs/1807.02004) using the exact same UW3 data split. According to your paper, there are 

- 72,807 GT lines for training
- 9,729 GT lines for evaluation

However, from the data I downloaded from http://tmbdev.net/ocrdata-split/, I have 

- 86,751 GT lines for training
- 9,730 GT lines for evaluation

Am I not supposed to use all the data from the website?

**Comment by ChWick** [comment]
Thanks for this very important information. Our dataset does not contain (maybe the extractor crashed or the download failed) the book dirs 0000 to 0315 in the training set which is exactly this missing count...
The single line in the evaluation should be a line which has a width of 0 when rescaling to a height of 48px and is therefore ignored by Calamari. Most probably this is a line that was rotated by 90 degrees.

**Comment by ChWick** [comment]
This should be correct! I extracted everything anew and got your upper counts for train and evaluation.

Obviously even the 316 dir was not fully extracted (100 lines with 70K Characters are missing). The codec discrepancy of 2 occurs possibly due to our postprocessing of chars (unicode roman digits to latin chars, quotes, ...)

**Comment by alwc** [comment]
I see, thanks for the info.
