### ISSUE TITLE
use a pre-trained model

### ISSUE THREAD

**Issue by HounaidaMoalla** [Calamari-OCR/calamari#69]
Hello.
By executing the command 
calamari-train --files pathOfDataSet/*.bin.png --weights pathOfPretrainedModel/model_number.ckpt --checkpoint_frequency 1000 --output_dir pathOfOutputModels
I have the impression that the train recommenced again : it did not take the weights of the pre-trained model.
thanks for the help

**Comment by ChWick** [comment]
You should see a huge difference between training with and without

**Comment by ChWick** [comment]
You should see a huge difference between training with and without using `--weights`, especially in the time it consumes to get the first meaningful results.
However, since the last layer of the neural net is not 'copied' fully (possible changes of the alphabet)  and your lines are not fully similar to the training data set of the pretrainined model, the pretraining yields also 'garbage' for the first few iterations.
However, as said, training using a pretrained model should converge way faster.

**Comment by HounaidaMoalla** [comment]
@ChWick 
thank you very much

**Comment by HounaidaMoalla** [comment]
@ChWick
Dear, 
Please, if I want to execute Calamari with only one layer LSTM , is  the following command correct :

calamari-train --files DatasetPath –network lstm=200 --checkpoint_frequency 1000 --output_dir modelsLSTM200

Thank you
