### ISSUE TITLE
Any lead on annotation tool for dataset creation

### ISSUE THREAD

**Issue by thak123** [Calamari-OCR/calamari#75]
Hi, I am trying to use ICDAR dataset for training a OCR model using calamari.

Can anyone suggest any good tool for creating the ground truth data from ICDAR.

Also does the images which are fed into network, have to be resized to a particular dimension(32px height vs 100 px width) or aspect ration ?

**Comment by bjmrevilla** [comment]
Have you tried `labelimg` (https://github.com/tzutalin/labelImg)?

**Comment by ChWick** [comment]
Hi, what dataset are you using exactly? Calamari can only act on line images, full pages must be segmented first (e.g. by OCRopus).
For GT annotation of lines, we use my tool published (here)[https://github.com/ChWick/ocrgtannotator/].

The network will itself resize the line image height to 48px, which can be changed by a parameter during training.
The width is arbitrary, therefore you should simply keep the original aspect ratio.

**Comment by thak123** [comment]
I tried to use the https://github.com/ChWick/ocrgtannotator/ tool but couldn't get images to be displayed in browser.
It shows the folder under storage folder but no images are shown

**Comment by ChWick** [comment]
Oh, sorry, I forget to mention, that the file extension currently is `nrm.png` (as produced by OCRopus).
However you can change this very easily [here](https://github.com/ChWick/ocrgtannotator/blob/366513ac0c49cae6f6bf3c543a1214d7689c8a15/server/database/database.py#L13).

**Comment by jeanm** [comment]
I've found this very simple script to do the trick for me:
```
for i in *.gt.txt; do open -g -a Preview ${i%%.*}.bin.png && vim $i || break; done
```
It works on macOS, although I'm sure there's a simple equivalent for Linux. Text files are opened in Vim and images are opened in Preview (the `-g` flag makes it stay in the background so the terminal stays focussed). Once you're done fixing a text file, save and exit Vim. The new text file and image will open automatically in the same windows. You'll want to arrange the windows so that they stay side by side, and select "Zoom to fit" in Preview.
